# 应用信息配置
application:
  name: '@application.name@'
  version: '@application.version@'
  base-package: cn.people.bliss
  description: ''
# 服务信息
server:
  port: 8081
  servlet:
    context-path: /bliss